#!/usr/bin/env python3
"""
Regional memo aggregator.

Reads each MD-1 director's `trends.json` envelope (already produced by
`land_brief.py`) and rolls them up into per-region memos. The 9 MD-1
directors map to 3 regions (with sub-region notes preserved):

  NA    — Megan Miceli (Canada), Patrick Gaughan (NA Asset Management),
          Adam Steinhouse (US Pension & Insurance)
  EMEA  — Sarah Pittroff (Central Europe), Francois Thaury (Southern
          Europe), Dan Peppett (UK & Ireland), Christian Ebbesen (NL &
          Nordics), Mourad (Middle East & Africa)
  APAC  — Jesper Tyrer (APAC)

For each region, the memo surfaces:
  - Top recurring action-item themes across the region's directors
  - Total ARR + ACV in pipeline
  - HIGH-priority actions across all directors, sorted by claim severity
  - Per-director action summary (1 line each)

Output: `state/<period>/__regional__/<region-slug>.md`

Usage:
    python3 scripts/regional_memo.py --period 2026-Q2

Idempotent: overwrites existing memos for the period.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import Counter
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATE_DIR = ROOT / "state"

# Region → list of director names (must match canonical names in scripts/_directors.py)
REGIONS: dict[str, list[str]] = {
    "NA": ["Megan Miceli", "Patrick Gaughan", "Adam Steinhouse"],
    "EMEA": [
        "Sarah Pittroff",
        "Francois Thaury",
        "Dan Peppett",
        "Christian Ebbesen",
        "Mourad",
    ],
    "APAC": ["Jesper Tyrer"],
}

PRIORITY_RANK = {"high": 0, "medium": 1, "low": 2}


def _load_envelope(period: str, director_name: str) -> dict[str, Any] | None:
    slug = director_name.replace(" ", "-")
    p = STATE_DIR / period / slug / "trends.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())


def _kpi(envelope: dict, name: str) -> float:
    """Read a top-level KPI value by name; 0 if missing."""
    for k in envelope.get("kpis") or []:
        if k.get("name") == name:
            return float(k.get("value") or 0)
    return 0.0


def render_region_memo(region: str, period: str, envelopes: list[dict]) -> str:
    if not envelopes:
        return f"# {region} regional memo — {period}\n\n_No director envelopes found._\n"

    total_arr = sum(_kpi(e, "total_pipeline_arr") for e in envelopes)
    total_beyond = sum(_kpi(e, "pipeline_arr_beyond_cfq") for e in envelopes)
    total_acv = sum(_kpi(e, "total_renewal_acv") for e in envelopes)
    all_actions: list[dict] = []
    for e in envelopes:
        for a in e.get("action_items") or []:
            a = dict(a)  # shallow copy, then enrich with director context
            a["_director"] = e.get("director", {}).get("name")
            a["_scope_label"] = e.get("director", {}).get("scope_label", "")
            all_actions.append(a)

    rule_counts = Counter(a["rule_id"] for a in all_actions)
    high_actions = sorted(
        [a for a in all_actions if a.get("priority") == "high"],
        key=lambda a: a.get("rule_id", ""),
    )

    lines = [
        f"# {region} regional memo — {period}",
        "",
        "*Internal SimCorp regional rollup. Generated by "
        "`scripts/regional_memo.py` — derived from each director's locked "
        "trends.json envelope (schema_version=2; LLM-bound envelope is "
        "aggregate-only per AI Code of Conduct §8). Not for redistribution.*",
        "",
        "## Region snapshot",
        "",
        f"- **Directors covered:** {len(envelopes)}",
        f"- **{period} closeable Land+Expand ARR:** EUR {total_arr:,.0f}",
        f"- **Open Land+Expand beyond {period}:** EUR {total_beyond:,.0f} "
        f"_(out-of-quarter pipe — context, not in CFQ forecast)_",
        f"- **{period} renewal ACV:** EUR {total_acv:,.0f}",
        f"- **Total action items across the region:** {len(all_actions)}",
        f"- **HIGH-priority actions:** {sum(1 for a in all_actions if a.get('priority') == 'high')}",
        "",
        "## Recurring themes (action-item frequency across directors)",
        "",
        "| Rule | Hits | Affected directors |",
        "|---|---:|---|",
    ]
    # Sort by frequency desc
    for rule_id, n in rule_counts.most_common():
        affected = sorted({a["_director"] for a in all_actions if a["rule_id"] == rule_id})
        lines.append(f"| `{rule_id}` | {n} | {', '.join(affected)} |")
    lines.append("")

    if high_actions:
        lines += [
            "## Region HIGH-priority queue",
            "",
            "*Each HIGH action below is owned by a single director. The MD-1 "
            "leadership review should ensure these are addressed before EOM.*",
            "",
            "| # | Director | Rule | Claim | Suggested action |",
            "|---|---|---|---|---|",
        ]
        for i, a in enumerate(high_actions, 1):
            lines.append(
                f"| {i} | {a['_director']} ({a['_scope_label']}) | `{a['rule_id']}` | "
                f"{a['claim']} | {a['suggested_action']} |"
            )
        lines.append("")

    lines += [
        "## Director-by-director action summary",
        "",
        f"| Director | Scope | {period} ARR | Beyond {period} | {period} ACV | # Actions | Themes |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for e in envelopes:
        d = e.get("director") or {}
        actions = e.get("action_items") or []
        themes = ", ".join(sorted({a["rule_id"] for a in actions})) or "(none)"
        lines.append(
            f"| {d.get('name')} | {d.get('scope_label', '')} | "
            f"EUR {_kpi(e, 'total_pipeline_arr'):,.0f} | "
            f"EUR {_kpi(e, 'pipeline_arr_beyond_cfq'):,.0f} | "
            f"EUR {_kpi(e, 'total_renewal_acv'):,.0f} | "
            f"{len(actions)} | {themes} |"
        )
    lines.append("")

    lines += [
        "## What this means for next month",
        "",
        f"The region's most common action-item theme is "
        f"`{rule_counts.most_common(1)[0][0]}` "
        f"({rule_counts.most_common(1)[0][1]} of {len(envelopes)} directors). "
        "If the same theme recurs three months in a row, escalate to a "
        "process review (Commercial Approval policy, account-coverage "
        "playbook, activity SLA — depending on the rule).",
        "",
        "Compliance: this memo aggregates per-director numbers only — no "
        "per-deal, per-account, or per-rep detail. Suitable for MD-1 "
        "leadership review (Hanen Borchani et al). Do NOT distribute "
        "outside the leadership group without a Group Compliance review.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--period", required=True, help="e.g., 2026-Q2")
    args = ap.parse_args()

    period_dir = STATE_DIR / args.period
    if not period_dir.exists():
        print(f"ERROR: no director artifacts at {period_dir}", file=sys.stderr)
        return 1

    out_dir = period_dir / "__regional__"
    out_dir.mkdir(exist_ok=True)

    written: list[pathlib.Path] = []
    for region, director_names in REGIONS.items():
        envelopes = []
        missing = []
        for name in director_names:
            env = _load_envelope(args.period, name)
            if env is None:
                missing.append(name)
            else:
                envelopes.append(env)
        if missing:
            print(f"  [WARN] {region}: missing envelopes for {missing}", file=sys.stderr)
        memo = render_region_memo(region, args.period, envelopes)
        memo_path = out_dir / f"{region.lower()}.md"
        memo_path.write_text(memo)
        written.append(memo_path)
        print(f"→ {region:6s} ({len(envelopes)}/{len(director_names)} dirs) → {memo_path}")

    print(f"\n✓ {len(written)} regional memo(s) written to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
